# Generated by Django 5.2.7 on 2025-10-21 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gso_accounts', '0001_initial'),
        ('gso_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords to match against request description')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuccessIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('activity_name', models.ForeignKey(blank=True, help_text='Select the Activity Name that maps to this Success Indicator', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gso_reports.activityname')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gso_accounts.unit')),
            ],
        ),
        migrations.CreateModel(
            name='WorkAccomplishmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateField()),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('activity_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Completed', max_length=50)),
                ('material_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('control_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_personnel', models.ManyToManyField(blank=True, related_name='war_personnel', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='war', to='gso_requests.servicerequest')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gso_accounts.unit')),
            ],
        ),
        migrations.CreateModel(
            name='IPMT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('accomplishment', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gso_accounts.unit')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gso_reports.successindicator')),
                ('reports', models.ManyToManyField(blank=True, to='gso_reports.workaccomplishmentreport')),
            ],
        ),
    ]
