# Generated by Django 5.2.7 on 2025-10-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gso_reports', '0002_workaccomplishmentreport_personnel_names_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workaccomplishmentreport',
            name='personnel_names',
        ),
        migrations.RemoveField(
            model_name='workaccomplishmentreport',
            name='requesting_office_name',
        ),
    ]
