# Generated by Django 5.2.7 on 2025-10-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gso_reports', '0003_remove_workaccomplishmentreport_personnel_names_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workaccomplishmentreport',
            name='personnel_names',
            field=models.TextField(blank=True, help_text='Comma-separated names for migrated WARs', null=True),
        ),
        migrations.AddField(
            model_name='workaccomplishmentreport',
            name='requesting_office_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
