# Generated by Django 5.2.7 on 2025-10-21 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gso_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit_of_measurement', models.CharField(default='pcs', help_text='Unit of measurement (e.g., pcs, liters, meters, box, set)', max_length=50)),
                ('category', models.CharField(blank=True, help_text='Category (e.g., Electrical, Furniture, Tools, Cleaning)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gso_accounts.unit')),
            ],
        ),
    ]
