# Generated by Django 5.2.7 on 2025-10-28 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gso_reports', '0005_remove_successindicator_activity_name_and_more'),
        ('gso_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='selected_indicator',
            field=models.ForeignKey(blank=True, help_text='Temporary field where personnel can choose success indicator before WAR generation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for_requests', to='gso_reports.successindicator'),
        ),
    ]
