# Generated by Django 5.2.7 on 2025-11-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gso_requests', '0002_servicerequest_selected_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='request_attachments/'),
        ),
    ]
