# Generated by Django 5.2.7 on 2025-11-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gso_requests', '0004_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
    ]
