# Generated by Django 5.2.7 on 2025-10-28 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gso_reports', '0004_workaccomplishmentreport_personnel_names_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='successindicator',
            name='activity_name',
        ),
        migrations.AddField(
            model_name='workaccomplishmentreport',
            name='success_indicator',
            field=models.ForeignKey(blank=True, help_text='Selected success indicator relevant to this work', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wars', to='gso_reports.successindicator'),
        ),
        migrations.DeleteModel(
            name='ActivityName',
        ),
    ]
