# Generated by Django 5.2.7 on 2025-10-21 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gso_accounts', '0001_initial'),
        ('gso_migration', '0005_migrationupload_delete_datamigration'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationupload',
            name='target_unit',
            field=models.ForeignKey(blank=True, help_text='Select the Unit where this data belongs', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gso_accounts.unit'),
        ),
    ]
