# Generated by Django 5.2.7 on 2025-10-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='migrations/')),
                ('migration_type', models.CharField(choices=[('reports', 'Work Accomplishment Reports'), ('ipmt', 'IPMT Records'), ('inventory', 'Inventory Items'), ('requests', 'Service Requests')], max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('result_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
