# Generated by Django 5.2.7 on 2025-10-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gso_migration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='migrations/')),
                ('target_model', models.CharField(choices=[('apps.gso_reports.WorkAccomplishmentReport', 'Work Accomplishment Reports'), ('apps.gso_inventory.InventoryItem', 'Inventory Items'), ('apps.gso_requests.ServiceRequest', 'Service Requests'), ('apps.gso_reports.IPMT', 'IPMT Records')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MigrationBatch',
        ),
    ]
