# Generated by Django 5.2.7 on 2025-10-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gso_migration', '0002_datamigration_delete_migrationbatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamigration',
            name='target_model',
            field=models.CharField(choices=[('gso_reports.WorkAccomplishmentReport', 'Work Accomplishment Reports'), ('gso_inventory.InventoryItem', 'Inventory Items'), ('gso_requests.ServiceRequest', 'Service Requests'), ('gso_reports.IPMT', 'IPMT Records')], max_length=100),
        ),
    ]
