# Generated by Django 5.2.7 on 2025-10-21 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gso_migration', '0004_alter_datamigration_target_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='migration_files/')),
                ('migration_type', models.CharField(choices=[('WORK_REPORT', 'Work Accomplishment Report'), ('IPMT', 'IPMT Records'), ('INVENTORY', 'Inventory Items'), ('SERVICE_REQUEST', 'Service Requests')], max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('result_message', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Migration',
                'verbose_name_plural': 'Data Migrations',
            },
        ),
        migrations.DeleteModel(
            name='DataMigration',
        ),
    ]
