# Generated by Django 5.2.7 on 2025-10-21 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gso_accounts', '0001_initial'),
        ('gso_inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gso_inventory.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('custom_contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('activity_name', models.CharField(blank=True, help_text='Short standardized activity name (auto-mapped from description)', max_length=255, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('In Progress', 'In Progress'), ('Done for Review', 'Done for Review'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_personnel', models.ManyToManyField(blank=True, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gso_accounts.department')),
                ('materials', models.ManyToManyField(blank=True, related_name='requests', through='gso_requests.RequestMaterial', to='gso_inventory.inventoryitem')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gso_accounts.unit')),
            ],
        ),
        migrations.AddField(
            model_name='requestmaterial',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gso_requests.servicerequest'),
        ),
        migrations.CreateModel(
            name='TaskReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='gso_requests.servicerequest')),
            ],
        ),
    ]
