# Generated by Django 5.2.7 on 2025-11-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gso_requests', '0003_servicerequest_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('In Progress', 'In Progress'), ('Done for Review', 'Done for Review'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Emergency', 'Emergency')], default='Pending', max_length=20),
        ),
    ]
