# Generated by Django 5.2.7 on 2025-11-12 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gso_requests', '0005_servicerequest_is_emergency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc1', models.CharField(blank=True, max_length=200, verbose_name="Awareness of Citizen's Charter")),
                ('cc2', models.CharField(blank=True, max_length=200, verbose_name='Knowledge of Office CC')),
                ('cc3', models.CharField(blank=True, max_length=200, verbose_name='Usefulness of CC')),
                ('sqd1', models.IntegerField(blank=True, null=True, verbose_name='Staff were courteous and helpful')),
                ('sqd2', models.IntegerField(blank=True, null=True, verbose_name='Spent reasonable time for transaction')),
                ('sqd3', models.IntegerField(blank=True, null=True, verbose_name='Clear communication during process')),
                ('sqd4', models.IntegerField(blank=True, null=True, verbose_name='Accessible and adequate facilities')),
                ('sqd5', models.IntegerField(blank=True, null=True, verbose_name='Equipped and knowledgeable staff')),
                ('sqd6', models.IntegerField(blank=True, null=True, verbose_name='Transparent and fair service')),
                ('sqd7', models.IntegerField(blank=True, null=True, verbose_name='Services met expectations')),
                ('sqd8', models.IntegerField(blank=True, null=True, verbose_name='Satisfied with overall experience')),
                ('sqd9', models.IntegerField(blank=True, null=True, verbose_name='Would recommend the service')),
                ('suggestions', models.TextField(blank=True, verbose_name='Suggestions for improvement')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email address (optional)')),
                ('average_score', models.FloatField(default=0, verbose_name='Average satisfaction score')),
                ('sentiment', models.CharField(blank=True, max_length=20, verbose_name='Sentiment (AI-generated)')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible in reports')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='gso_requests.servicerequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
