# Generated by Django 5.2.7 on 2025-11-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gso_requests', '0006_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-is_emergency', '-created_at']},
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='schedule_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='schedule_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='schedule_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
