# Generated by Django 5.2.7 on 2025-11-12 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gso_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_units', to=settings.AUTH_USER_MODEL),
        ),
    ]
